# Generated by Django 3.1.7 on 2021-04-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=1)),
                ('coin', models.CharField(choices=[('ada', 'ada'), ('btc', 'btc'), ('usdt', 'usdt'), ('iost', 'iost'), ('near', 'near'), ('wan', 'wan')], default='ada', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocket_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField()),
                ('money', models.IntegerField()),
            ],
        ),
    ]
